/**
 * Internationalisation
 */

var i18n = {};

i18n.en = {
    help_image_url: '/gfx/loc/en/helpLink.gif',
    configuration_panel_title: 'Die2Nite Enhancer - Settings',
    configuration_panel_script_description: 'Die2Nite Enhancer allows you to enhance your game experience, every features can be controlled from this panel.',
    configuration_panel_enable_shortcuts: 'Enable shortcuts',
    configuration_panel_enable_shortcuts_tooltip: 'Let you use keyboard shortcuts in town to quickly access important places (e.g.: banks, gates).',
    configuration_panel_hide_hero_adds: 'Hide hero adds',
    configuration_panel_hide_hero_adds_tooltip: 'Hide the adds for the hero mode on all the website. Can be useful if you are already hero or don\'t want to be one.',
    configuration_panel_highlight_ap: 'Highlight AP',
    configuration_panel_highlight_ap_tooltip: 'Add a border with a specific color (from red to green) in function of the remaining number of action point.',
    configuration_panel_hide_help: 'Hide help',
    configuration_panel_hide_help_tooltip: 'Hide all the helps in the interface.',
    configuration_panel_hide_twinoid_bar: 'Hide Twinoid bar',
    configuration_panel_hide_twinoid_bar_tooltip: 'Hide the Twinoid black bar at the top of the screen. Put your mouse near the top of the screen to show it again.',
    configuration_panel_hide_footer: 'Hide footer',
    configuration_panel_hide_footer_tooltip: 'Hide the page footer with informations about other games, Motion Twin, etc...',
    configuration_panel_hide_pegi: 'Hide PEGI logo',
    configuration_panel_hide_pegi_tooltip: 'Hide the PEGI logo at the bottom of each page.',
    configuration_panel_hide_rookie_mode: 'Hide rookie mode',
    configuration_panel_hide_rookie_mode_tooltip: 'Hide all the links to enable the rookie mode.',
    configuration_panel_hide_rp_content: 'Hide RP content',
    configuration_panel_hide_rp_content_tooltip: 'Hide all the RP content.',
    configuration_panel_enable_duskdawn_sync: 'Enable Dusk Dawn sync',
    configuration_panel_enable_duskdawn_sync_tooltip: 'Add the possibility to sync with Dusk Dawn',
    configuration_panel_enable_mapviewer_sync: 'Enable Map Viewer sync',
    configuration_panel_enable_mapviewer_sync_tooltip: 'Add the possibility to sync with Map Viewer',
    configuration_panel_enable_construction_max_ap: 'Use max AP in constructions',
    configuration_panel_enable_construction_max_ap_tooltip: 'While in the construction page, use your actual number of AP instead of the default 1 AP.',
    configuration_panel_hide_completed_constructions: 'Hide completed constructions',
    configuration_panel_hide_completed_constructions_tooltip: 'While in the construction page, hide all the completed ones.',
    configuration_panel_enable_hero_bar_stat: 'Enable hero bar stat',
    configuration_panel_enable_hero_bar_stat_tooltip: 'On soul page, enable days stat on the hero bar.',
    configuration_panel_enable_cyanide_protection: 'Enable cyanide protection',
    configuration_panel_enable_cyanide_protection_tooltip: 'Avoid to eat cyanide by accident by deleting the concerning link in your home.',
    configuration_panel_save_button: 'Save',
    external_tools_bar_update: 'Update external tools'
};

i18n.fr = {
    help_image_url: '/gfx/loc/fr/helpLink.gif',
    configuration_panel_title: 'Die2Nite Enhancer - Paramètres',
    configuration_panel_script_description: 'Die2Nite Enhancer vous permet d\'améliorer votre expérience de jeu, toutes les fonctionalités peuvent être controlées depuis ce panneau de configuration.',
    configuration_panel_enable_shortcuts: 'Activer les raccourcis',
    configuration_panel_enable_shortcuts_tooltip: 'Active des raccourcis claviers pour accéder rapidement aux places importantes en ville (e.g.: la banque, les portes).',
    configuration_panel_hide_hero_adds: 'Cacher les pubs pour le mode héros',
    configuration_panel_hide_hero_adds_tooltip: 'Cache les pubs pour le mode héros sur tout le site. C\'est pratique si vous êtes déjà héros ou si vous ne comptez pas le devenir.',
    configuration_panel_highlight_ap: 'Colorer les PA',
    configuration_panel_highlight_ap_tooltip: 'Ajoute une bordure avec une couleur spécifique (du rouge au vert) en fonction du nombre de PA restant.',
    configuration_panel_hide_help: 'Cacher les aides',
    configuration_panel_hide_help_tooltip: 'Cache les aides de jeu dans toute l\'interface.',
    configuration_panel_hide_twinoid_bar: 'Cacher la barre Twinoid',
    configuration_panel_hide_twinoid_bar_tooltip: 'Cache la barre Twinoid en haut de l\'écran. Rapprochez votre souris en haut de l\'écran pour l\'afficher à nouveau.',
    configuration_panel_hide_footer: 'Cacher le bas de page',
    configuration_panel_hide_footer_tooltip: 'Cache le bas de page contenant des informations à propos des autres jeux de Motion Twin, etc...',
    configuration_panel_hide_pegi: 'Cacher le logo PEGI',
    configuration_panel_hide_pegi_tooltip: 'Cache le logo PEGI en bas de page.',
    configuration_panel_hide_rookie_mode: 'Cacher le mode apprentissage',
    configuration_panel_hide_rookie_mode_tooltip: 'Cache tous les liens pour activer le mode apprentissage.',
    configuration_panel_hide_rp_content: 'Cacher le contenu RP',
    configuration_panel_hide_rp_content_tooltip: 'Cache le contenu RP (Role-Play).',
    configuration_panel_enable_bbh_sync: 'Activer la sync. BBH',
    configuration_panel_enable_bbh_sync_tooltip: 'Ajoute la possibilité de synchroniser avec BigBroth\'Hordes.',
    configuration_panel_enable_oeev_sync: 'Activer la sync. OEEV',
    configuration_panel_enable_oeev_sync_tooltip: 'Ajoute la possibilité de synchroniser avec Où en êtes-vous ?',
    configuration_panel_enable_construction_max_ap: 'Constructions PA max',
    configuration_panel_enable_construction_max_ap_tooltip: 'Utilise le maximum de PA disponible pour les constructions au lieu de 1 par défault.',
    configuration_panel_hide_completed_constructions: 'Cacher constructions finies',
    configuration_panel_hide_completed_constructions_tooltip: 'Cache les constructions finies.',
    configuration_panel_enable_hero_bar_stat: 'Activer stats barre héro',
    configuration_panel_enable_hero_bar_stat_tooltip: 'Sur la page d\'âme, active le pourcentage de la barre héros.',
    configuration_panel_enable_cyanide_protection: 'Activer la protection au cyanure',
    configuration_panel_enable_cyanide_protection_tooltip: 'Evite de s\'empoisonner au cyanure par accident en supprimant le lien concerné dans votre maison.',
    configuration_panel_save_button: 'Sauvegarder',
    external_tools_bar_update: 'Mettre à jour les outils externes'
};

i18n.es = {
    help_image_url: '/gfx/loc/es/helpLink.gif',
    configuration_panel_title: 'Die2Nite Enhancer - Settings',
    configuration_panel_script_description: 'Die2Nite Enhancer allows you to enhance your game experience, every features can be controlled from this panel.',
    configuration_panel_enable_shortcuts: 'Enable shortcuts',
    configuration_panel_enable_shortcuts_tooltip: 'Let you use keyboard shortcuts in town to quickly access important places (e.g.: banks, gates).',
    configuration_panel_hide_hero_adds: 'Hide hero adds',
    configuration_panel_hide_hero_adds_tooltip: 'Hide the adds for the hero mode on all the website. Can be useful if you are already hero or don\'t want to be one.',
    configuration_panel_highlight_ap: 'Highlight AP',
    configuration_panel_highlight_ap_tooltip: 'Add a border with a specific color (from red to green) in function of the remaining number of action point.',
    configuration_panel_hide_help: 'Hide help',
    configuration_panel_hide_help_tooltip: 'Hide all the helps in the interface.',
    configuration_panel_hide_twinoid_bar: 'Hide Twinoid bar',
    configuration_panel_hide_twinoid_bar_tooltip: 'Hide the Twinoid black bar at the top of the screen. Put your mouse near the top of the screen to show it again.',
    configuration_panel_hide_footer: 'Hide footer',
    configuration_panel_hide_footer_tooltip: 'Hide the page footer with informations about other games, Motion Twin, etc...',
    configuration_panel_hide_pegi: 'Hide PEGI',
    configuration_panel_hide_pegi_tooltip: 'Hide the PEGI image at the bottom of each page.',
    configuration_panel_hide_rookie_mode: 'Hide rookie mode',
    configuration_panel_hide_rookie_mode_tooltip: 'Hide all the links to enable the rookie mode.',
    configuration_panel_hide_rp_content: 'Hide RP content',
    configuration_panel_hide_rp_content_tooltip: 'Hide all the RP content.',
    configuration_panel_enable_construction_max_ap: 'Use max AP in constructions',
    configuration_panel_enable_construction_max_ap_tooltip: 'While in the construction page, use your actual number of AP instead of the default 1 AP.',
    configuration_panel_hide_completed_constructions: 'Hide completed constructions',
    configuration_panel_hide_completed_constructions_tooltip: 'While in the construction page, hide all the completed ones.',
    configuration_panel_enable_hero_bar_stat: 'Enable hero bar stat',
    configuration_panel_enable_hero_bar_stat_tooltip: 'On soul page, enable days stat on the hero bar.',
    configuration_panel_enable_cyanide_protection: 'Enable cyanide protection',
    configuration_panel_enable_cyanide_protection_tooltip: 'Avoid to eat cyanide by accident by deleting the concerning link in your home.',
    configuration_panel_save_button: 'Save',
    external_tools_bar_update: 'Update external tools'
};

i18n.de = {
    help_image_url: '/gfx/loc/de/helpLink.gif',
    configuration_panel_title: 'Die2Nite Enhancer - Settings',
    configuration_panel_script_description: 'Die2Nite Enhancer allows you to enhance your game experience, every features can be controlled from this panel.',
    configuration_panel_enable_shortcuts: 'Enable shortcuts',
    configuration_panel_enable_shortcuts_tooltip: 'Let you use keyboard shortcuts in town to quickly access important places (e.g.: banks, gates).',
    configuration_panel_hide_hero_adds: 'Hide hero adds',
    configuration_panel_hide_hero_adds_tooltip: 'Hide the adds for the hero mode on all the website. Can be useful if you are already hero or don\'t want to be one.',
    configuration_panel_highlight_ap: 'Highlight AP',
    configuration_panel_highlight_ap_tooltip: 'Add a border with a specific color (from red to green) in function of the remaining number of action point.',
    configuration_panel_hide_help: 'Hide help',
    configuration_panel_hide_help_tooltip: 'Hide all the helps in the interface.',
    configuration_panel_hide_twinoid_bar: 'Hide Twinoid bar',
    configuration_panel_hide_twinoid_bar_tooltip: 'Hide the Twinoid black bar at the top of the screen. Put your mouse near the top of the screen to show it again.',
    configuration_panel_hide_footer: 'Hide footer',
    configuration_panel_hide_footer_tooltip: 'Hide the page footer with informations about other games, Motion Twin, etc...',
    configuration_panel_hide_pegi: 'Hide PEGI',
    configuration_panel_hide_pegi_tooltip: 'Hide the PEGI image at the bottom of each page.',
    configuration_panel_hide_rookie_mode: 'Hide rookie mode',
    configuration_panel_hide_rookie_mode_tooltip: 'Hide all the links to enable the rookie mode.',
    configuration_panel_hide_rp_content: 'Hide RP content',
    configuration_panel_hide_rp_content_tooltip: 'Hide all the RP content.',
    configuration_panel_enable_construction_max_ap: 'Use max AP in constructions',
    configuration_panel_enable_construction_max_ap_tooltip: 'While in the construction page, use your actual number of AP instead of the default 1 AP.',
    configuration_panel_hide_completed_constructions: 'Hide completed constructions',
    configuration_panel_hide_completed_constructions_tooltip: 'While in the construction page, hide all the completed ones.',
    configuration_panel_enable_hero_bar_stat: 'Enable hero bar stat',
    configuration_panel_enable_hero_bar_stat_tooltip: 'On soul page, enable days stat on the hero bar.',
    configuration_panel_enable_cyanide_protection: 'Enable cyanide protection',
    configuration_panel_enable_cyanide_protection_tooltip: 'Avoid to eat cyanide by accident by deleting the concerning link in your home.',
    configuration_panel_save_button: 'Save',
    external_tools_bar_update: 'Update external tools'
};
