/**
 * Internationalisation
 */

var i18n = {};

i18n.en = {
    help_image_url: '/gfx/loc/en/helpLink.gif',
    configuration_panel_title: 'Die2Nite Enhancer - Settings',
    configuration_panel_script_description: 'Die2Nite Enhancer allows you to enhance your game experience, every features can be controlled from this panel.',
    configuration_panel_title_citizen: 'Citizen',
    configuration_panel_title_hero: 'Hero',
    configuration_panel_title_sync: 'External tools',
    configuration_panel_title_hide: 'Interface',
    configuration_panel_enable_shortcuts: 'Enable shortcuts',
    configuration_panel_enable_shortcuts_tooltip: 'Let you use keyboard shortcuts in town to quickly access important places (e.g.: banks, gates).',
    configuration_panel_hide_hero_adds: 'Hide hero adds',
    configuration_panel_hide_hero_adds_tooltip: 'Hide the adds for the hero mode on all the website. Can be useful if you are already hero or don\'t want to be one.',
    configuration_panel_highlight_ap: 'Highlight AP',
    configuration_panel_highlight_ap_tooltip: 'Add a border with a specific color (from red to green) in function of the remaining number of action point.',
    configuration_panel_hide_help: 'Hide help',
    configuration_panel_hide_help_tooltip: 'Hide all the helps in the interface.',
    configuration_panel_hide_twinoid_bar: 'Hide Twinoid bar',
    configuration_panel_hide_twinoid_bar_tooltip: 'Hide the Twinoid black bar at the top of the screen. Put your mouse near the top of the screen to show it again.',
    configuration_panel_hide_footer: 'Hide footer',
    configuration_panel_hide_footer_tooltip: 'Hide the page footer with informations about other games, Motion Twin, etc...',
    configuration_panel_hide_pegi: 'Hide PEGI logo',
    configuration_panel_hide_pegi_tooltip: 'Hide the PEGI logo at the bottom of each page.',
    configuration_panel_hide_rookie_mode: 'Hide rookie mode',
    configuration_panel_hide_rookie_mode_tooltip: 'Hide all the links to enable the rookie mode.',
    configuration_panel_hide_rp_content: 'Hide RP content',
    configuration_panel_hide_rp_content_tooltip: 'Hide all the RP content.',
    configuration_panel_enable_duskdawn_sync: 'Enable Dusk Dawn sync',
    configuration_panel_enable_duskdawn_sync_tooltip: 'Add the possibility to sync with Dusk Dawn',
    configuration_panel_enable_mapviewer_sync: 'Enable Map Viewer sync',
    configuration_panel_enable_mapviewer_sync_tooltip: 'Add the possibility to sync with Map Viewer',
    configuration_panel_enable_construction_max_ap: 'Use max AP in constructions',
    configuration_panel_enable_construction_max_ap_tooltip: 'While in the construction page, use your actual number of AP instead of the default 1 AP.',
    configuration_panel_enable_hide_completed_constructions: 'Allow to hide completed constructions',
    configuration_panel_enable_hide_completed_constructions_tooltip: 'While on the construction page, add a link to hide all the completed constructions.',
    configuration_panel_enable_hero_bar_stat: 'Enable hero bar stat',
    configuration_panel_enable_hero_bar_stat_tooltip: 'On soul page, enable days stat on the hero bar.',
    configuration_panel_enable_cyanide_protection: 'Enable cyanide protection',
    configuration_panel_enable_cyanide_protection_tooltip: 'Avoid to eat cyanide by accident by deleting the link to use it.',
    configuration_panel_hide_twitter_share: 'Hide the Twitter share button',
    configuration_panel_hide_twitter_share_tooltip: 'Hide the Twitter share button on the Gazette.',
    configuration_panel_hide_city_outside_zones_banners: 'Hide the city and outside zones banners',
    configuration_panel_hide_city_outside_zones_banners_tooltip: 'Hide the banner on the top of the screen when in city or outside.',
    configuration_panel_save_button: 'Save',
    external_tools_bar_update: 'Update external tools',
    hide_completed_constructions: 'Hide completed constructions',
    show_completed_constructions: 'Show completed constructions'
};

i18n.fr = {
    help_image_url: '/gfx/loc/fr/helpLink.gif',
    configuration_panel_title: 'Die2Nite Enhancer - Paramètres',
    configuration_panel_script_description: 'Die2Nite Enhancer vous permet d\'améliorer votre expérience de jeu, toutes les fonctionalités peuvent être controlées depuis ce panneau de configuration.',
    configuration_panel_title_citizen: 'Citoyen',
    configuration_panel_title_hero: 'Héros',
    configuration_panel_title_sync: 'Outils externes',
    configuration_panel_title_hide: 'Interface',
    configuration_panel_enable_shortcuts: 'Activer les raccourcis',
    configuration_panel_enable_shortcuts_tooltip: 'Active des raccourcis claviers pour accéder rapidement aux places importantes en ville (e.g.: la banque, les portes).',
    configuration_panel_hide_hero_adds: 'Cacher les publicités pour le mode héros',
    configuration_panel_hide_hero_adds_tooltip: 'Cache les publicités pour le mode héros sur tout le site. C\'est pratique si vous êtes déjà héros ou si vous ne comptez pas le devenir.',
    configuration_panel_highlight_ap: 'Colorer les PA',
    configuration_panel_highlight_ap_tooltip: 'Ajoute une bordure avec une couleur spécifique (du rouge au vert) en fonction du nombre de PA restant.',
    configuration_panel_hide_help: 'Cacher les aides',
    configuration_panel_hide_help_tooltip: 'Cache les aides de jeu dans toute l\'interface.',
    configuration_panel_hide_twinoid_bar: 'Cacher la barre Twinoid',
    configuration_panel_hide_twinoid_bar_tooltip: 'Rabat la barre Twinoid en haut de l\'écran. Rapprochez votre souris du bord supérieur de l\'écran pour l\'afficher de nouveau.',
    configuration_panel_hide_footer: 'Cacher le pied de page',
    configuration_panel_hide_footer_tooltip: 'Cache le pied de page contenant des informations à propos des autres jeux de Motion Twin, etc...',
    configuration_panel_hide_pegi: 'Cacher le logo PEGI',
    configuration_panel_hide_pegi_tooltip: 'Cache le logo PEGI en bas de page.',
    configuration_panel_hide_rookie_mode: 'Cacher le mode apprentissage',
    configuration_panel_hide_rookie_mode_tooltip: 'Cache tous les liens pour activer le mode apprentissage.',
    configuration_panel_hide_rp_content: 'Cacher le contenu RP',
    configuration_panel_hide_rp_content_tooltip: 'Cache le contenu RP (Role-Play).',
    configuration_panel_enable_bbh_sync: 'Activer la synchronisation BBH',
    configuration_panel_enable_bbh_sync_tooltip: 'Ajoute la possibilité de synchroniser avec BigBroth\'Hordes.',
    configuration_panel_enable_oeev_sync: 'Activer la synchronisation OEEV',
    configuration_panel_enable_oeev_sync_tooltip: 'Ajoute la possibilité de synchroniser avec Où en êtes-vous ?',
    configuration_panel_enable_construction_max_ap: 'Construire avec un maximum de PA',
    configuration_panel_enable_construction_max_ap_tooltip: 'Utilise le maximum de PA disponible pour les constructions au lieu de 1 par défault.',
    configuration_panel_enable_hide_completed_constructions: 'Permettre de cacher les constructions finies',
    configuration_panel_enable_hide_completed_constructions_tooltip: 'Ajoute un lien dans la page constructions permettant de cacher les constructions finies.',
    configuration_panel_enable_hero_bar_stat: 'Activer le pourcentage sur la barre héros',
    configuration_panel_enable_hero_bar_stat_tooltip: 'Sur la page d\'âme, active le pourcentage sur la barre héros.',
    configuration_panel_enable_cyanide_protection: 'Protéger contre le cyanure',
    configuration_panel_enable_cyanide_protection_tooltip: 'Evite de s\'empoisonner au cyanure par accident en supprimant le lien permettant son utilisation.',
    configuration_panel_hide_twitter_share: 'Cacher le bouton de partage Twitter',
    configuration_panel_hide_twitter_share_tooltip: 'Cache le bouton de partage sur Twitter sur la page de la Gazette.',
    configuration_panel_hide_city_outside_zones_banners: 'Cacher la bannière en ville ou dehors',
    configuration_panel_hide_city_outside_zones_banners_tooltip: 'Cache l\'image en haut de l\'écran représentant le lieu où vous êtes quand vous vous situez en ville ou dehors.',
    configuration_panel_save_button: 'Sauvegarder',
    external_tools_bar_update: 'Mettre à jour les outils externes',
    hide_completed_constructions: 'Cacher les constructions finies',
    show_completed_constructions: 'Afficher les constructions finies'
};

i18n.es = {
    help_image_url: '/gfx/loc/es/helpLink.gif',
    configuration_panel_title: 'Die2Nite Enhancer - Settings',
    configuration_panel_script_description: 'Die2Nite Enhancer allows you to enhance your game experience, every features can be controlled from this panel.',
    configuration_panel_title_citizen: 'Citizen',
    configuration_panel_title_hero: 'Hero',
    configuration_panel_title_sync: 'External tools',
    configuration_panel_title_hide: 'Interface',
    configuration_panel_enable_shortcuts: 'Enable shortcuts',
    configuration_panel_enable_shortcuts_tooltip: 'Let you use keyboard shortcuts in town to quickly access important places (e.g.: banks, gates).',
    configuration_panel_hide_hero_adds: 'Hide hero adds',
    configuration_panel_hide_hero_adds_tooltip: 'Hide the adds for the hero mode on all the website. Can be useful if you are already hero or don\'t want to be one.',
    configuration_panel_highlight_ap: 'Highlight AP',
    configuration_panel_highlight_ap_tooltip: 'Add a border with a specific color (from red to green) in function of the remaining number of action point.',
    configuration_panel_hide_help: 'Hide help',
    configuration_panel_hide_help_tooltip: 'Hide all the helps in the interface.',
    configuration_panel_hide_twinoid_bar: 'Hide Twinoid bar',
    configuration_panel_hide_twinoid_bar_tooltip: 'Hide the Twinoid black bar at the top of the screen. Put your mouse near the top of the screen to show it again.',
    configuration_panel_hide_footer: 'Hide footer',
    configuration_panel_hide_footer_tooltip: 'Hide the page footer with informations about other games, Motion Twin, etc...',
    configuration_panel_hide_pegi: 'Hide PEGI',
    configuration_panel_hide_pegi_tooltip: 'Hide the PEGI image at the bottom of each page.',
    configuration_panel_hide_rookie_mode: 'Hide rookie mode',
    configuration_panel_hide_rookie_mode_tooltip: 'Hide all the links to enable the rookie mode.',
    configuration_panel_hide_rp_content: 'Hide RP content',
    configuration_panel_hide_rp_content_tooltip: 'Hide all the RP content.',
    configuration_panel_enable_construction_max_ap: 'Use max AP in constructions',
    configuration_panel_enable_construction_max_ap_tooltip: 'While in the construction page, use your actual number of AP instead of the default 1 AP.',
    configuration_panel_enable_hide_completed_constructions: 'Hide completed constructions',
    configuration_panel_enable_hide_completed_constructions_tooltip: 'While in the construction page, hide all the completed ones.',
    configuration_panel_enable_hero_bar_stat: 'Enable hero bar stat',
    configuration_panel_enable_hero_bar_stat_tooltip: 'On soul page, enable days stat on the hero bar.',
    configuration_panel_enable_cyanide_protection: 'Enable cyanide protection',
    configuration_panel_enable_cyanide_protection_tooltip: 'Avoid to eat cyanide by accident by deleting the link to use it.',
    configuration_panel_hide_twitter_share: 'Hide the Twitter share button',
    configuration_panel_hide_twitter_share_tooltip: 'Hide the Twitter share button on the Gazette.',
    configuration_panel_hide_city_outside_zones_banners: 'Hide the city and outside zones banners',
    configuration_panel_hide_city_outside_zones_banners_tooltip: 'Hide the banner on the top of the screen when in city or outside.',
    configuration_panel_save_button: 'Save',
    external_tools_bar_update: 'Update external tools',
    hide_completed_constructions: 'Hide completed constructions',
    show_completed_constructions: 'Show completed constructions'
};

i18n.de = {
    help_image_url: '/gfx/loc/de/helpLink.gif',
    configuration_panel_title: 'Die2Nite Enhancer - Settings',
    configuration_panel_script_description: 'Die2Nite Enhancer allows you to enhance your game experience, every features can be controlled from this panel.',
    configuration_panel_title_citizen: 'Citizen',
    configuration_panel_title_hero: 'Hero',
    configuration_panel_title_sync: 'External tools',
    configuration_panel_title_hide: 'Interface',
    configuration_panel_enable_shortcuts: 'Enable shortcuts',
    configuration_panel_enable_shortcuts_tooltip: 'Let you use keyboard shortcuts in town to quickly access important places (e.g.: banks, gates).',
    configuration_panel_hide_hero_adds: 'Hide hero adds',
    configuration_panel_hide_hero_adds_tooltip: 'Hide the adds for the hero mode on all the website. Can be useful if you are already hero or don\'t want to be one.',
    configuration_panel_highlight_ap: 'Highlight AP',
    configuration_panel_highlight_ap_tooltip: 'Add a border with a specific color (from red to green) in function of the remaining number of action point.',
    configuration_panel_hide_help: 'Hide help',
    configuration_panel_hide_help_tooltip: 'Hide all the helps in the interface.',
    configuration_panel_hide_twinoid_bar: 'Hide Twinoid bar',
    configuration_panel_hide_twinoid_bar_tooltip: 'Hide the Twinoid black bar at the top of the screen. Put your mouse near the top of the screen to show it again.',
    configuration_panel_hide_footer: 'Hide footer',
    configuration_panel_hide_footer_tooltip: 'Hide the page footer with informations about other games, Motion Twin, etc...',
    configuration_panel_hide_pegi: 'Hide PEGI',
    configuration_panel_hide_pegi_tooltip: 'Hide the PEGI image at the bottom of each page.',
    configuration_panel_hide_rookie_mode: 'Hide rookie mode',
    configuration_panel_hide_rookie_mode_tooltip: 'Hide all the links to enable the rookie mode.',
    configuration_panel_hide_rp_content: 'Hide RP content',
    configuration_panel_hide_rp_content_tooltip: 'Hide all the RP content.',
    configuration_panel_enable_construction_max_ap: 'Use max AP in constructions',
    configuration_panel_enable_construction_max_ap_tooltip: 'While in the construction page, use your actual number of AP instead of the default 1 AP.',
    configuration_panel_enable_hide_completed_constructions: 'Hide completed constructions',
    configuration_panel_enable_hide_completed_constructions_tooltip: 'While in the construction page, hide all the completed ones.',
    configuration_panel_enable_hero_bar_stat: 'Enable hero bar stat',
    configuration_panel_enable_hero_bar_stat_tooltip: 'On soul page, enable days stat on the hero bar.',
    configuration_panel_enable_cyanide_protection: 'Enable cyanide protection',
    configuration_panel_enable_cyanide_protection_tooltip: 'Avoid to eat cyanide by accident by deleting the link to use it.',
    configuration_panel_hide_twitter_share: 'Hide the Twitter share button',
    configuration_panel_hide_twitter_share_tooltip: 'Hide the Twitter share button on the Gazette.',
    configuration_panel_hide_city_outside_zones_banners: 'Hide the city and outside zones banners',
    configuration_panel_hide_city_outside_zones_banners_tooltip: 'Hide the banner on the top of the screen when in city or outside.',
    configuration_panel_save_button: 'Save',
    external_tools_bar_update: 'Update external tools',
    hide_completed_constructions: 'Hide completed constructions',
    show_completed_constructions: 'Show completed constructions'
};
